# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: unphased.ai
email: zachbela@alumni.stanford.edu
description: >- # this means to ignore newlines until "baseurl:"
    Solving hard optimization problems with asynchronous oscillators on FPGAs.
#baseurl: "/unphased.github.io" # the subpath of your site, e.g. /blog
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zbelateche.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: blip_tm
github_username:  zbelateche

syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

# Build settings
markdown: kramdown
#theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

github:
  is_project_page: false
  
show_downloads: true

color:
  header: "#000"
  gradient_left: "#4538eb"
  gradient_right: "#b50dd6"

buttons:
      zip_url: https://github.com/zbelateche/digial-ising
      zip_title: Check out the repo!
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Sign up for the waitlist!
      tar_hide: false
      discord_url: https://discord.gg/bkjgP5CY4G
      discord_title: Join the Discord!
      discord_hide: false
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
